"""Recreate resource and world_resources tables

Revision ID: 00fa6a590b57
Revises: e8f6b5a5c2db
Create Date: 2024-10-16 23:16:06.796377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fa6a590b57'
down_revision = 'e8f6b5a5c2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_resources', schema=None) as batch_op:
        batch_op.drop_column('rarity')

    # ### end Alembic commands ###
