"""empty message

Revision ID: 1e2c0f5148a5
Revises: 440dd3e44571
Create Date: 2024-10-16 23:39:11.511047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2c0f5148a5'
down_revision = '440dd3e44571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_resources', schema=None) as batch_op:
        batch_op.drop_column('world_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_limit', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
