"""added world_limit

Revision ID: 440dd3e44571
Revises: c9888be89175
Create Date: 2024-10-16 23:36:05.031498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440dd3e44571'
down_revision = 'c9888be89175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_resources', schema=None) as batch_op:
        batch_op.drop_column('world_limit')

    # ### end Alembic commands ###
