"""Added starting_area_id to characters table

Revision ID: 4b2c5a138b0b
Revises: 152fd2bb78cf
Create Date: 2024-10-17 22:43:17.974833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2c5a138b0b'
down_revision = '152fd2bb78cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_area_id', sa.Integer(), nullable=True, default=1))
        batch_op.create_foreign_key(None, 'starting_areas', ['starting_area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('starting_area_id')

    # ### end Alembic commands ###
