"""empty message

Revision ID: 55f1ad011bbc
Revises: 81d979fccbe7
Create Date: 2024-10-17 00:30:13.488030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f1ad011bbc'
down_revision = '81d979fccbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_resources', schema=None) as batch_op:
        batch_op.drop_constraint('character_resources_resource_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'world_resources', ['resource_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_resources_resource_id_fkey', 'resources', ['resource_id'], ['id'])

    # ### end Alembic commands ###
