"""empty message

Revision ID: 81d979fccbe7
Revises: 1e2c0f5148a5
Create Date: 2024-10-17 00:22:24.462954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d979fccbe7'
down_revision = '1e2c0f5148a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint('resources_resource_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('resources_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('resources_character_id_fkey', 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key('resources_resource_id_fkey', 'world_resources', ['resource_id'], ['id'])

    # ### end Alembic commands ###
