"""Recreate resources and world_resources tables

Revision ID: c9888be89175
Revises: 00fa6a590b57
Create Date: 2024-10-16 23:20:32.177744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9888be89175'
down_revision = '00fa6a590b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('resource_description', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['world_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_resources', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'resources', ['resource_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('resources')
    op.drop_table('world_resources')
    # ### end Alembic commands ###
