"""table update for starting areas

Revision ID: d0ee21b07523
Revises: b2c4a76f364b
Create Date: 2024-10-12 19:20:08.203118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ee21b07523'
down_revision = 'b2c4a76f364b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starting_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('skill_bonus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starting_area_skills',
    sa.Column('starting_area_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['starting_area_id'], ['starting_areas.id'], ),
    sa.PrimaryKeyConstraint('starting_area_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starting_area_skills')
    op.drop_table('starting_areas')
    # ### end Alembic commands ###
