"""Add foreign key constraint for world_resources

Revision ID: e8f6b5a5c2db
Revises: ee810b1e33f8
Create Date: 2024-10-16 22:24:42.461452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f6b5a5c2db'
down_revision = 'ee810b1e33f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_name'), ['name'], unique=False)

    op.create_table('world_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('resource_description', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('resource_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'world_resources', ['resource_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('description')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resource_id')
        batch_op.drop_column('character_id')
        batch_op.drop_column('quantity')

    op.drop_table('world_resources')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_name'))
        batch_op.drop_index(batch_op.f('ix_quests_id'))

    op.drop_table('quests')
    # ### end Alembic commands ###
