"""removing skill bonus from starting_areas

Revision ID: f0541df777b1
Revises: d0ee21b07523
Create Date: 2024-10-12 20:00:49.154184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0541df777b1'
down_revision = 'd0ee21b07523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starting_areas', schema=None) as batch_op:
        batch_op.drop_column('skill_bonus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starting_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_bonus', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
